version: "3.9"

services:
  orchestrator:
    image: blacktree/orchestrator:latest
    container_name: blacktree_orchestrator

    ports:
      - "5051:5051"
    environment:
      # Messaging Queue
      MQ_TYPE: rabbitmq
      MQ_URL: amqp://guest:guest@localhost:5672

      # GRPC
      ORCHESTRATOR_GRPC_PORT: 5051


    networks:
      blacktree-net:
        ipv4_address: 172.20.0.2


    restart: unless-stopped

  worker:
    image: blacktree/worker:latest

    deploy:
      replicas: 5

    environment:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: AKIAEXAMPLE123456
      AWS_SECRET_ACCESS_KEY: abc123exampleSECRETkey456789xyz
      ECR_REPO_URL: 1212828112.dkr.ecr.us-east-1.amazonaws.com

      ORCHESTRATOR_ADDR: orchestrator:5051

    depends_on:
      - orchestrator


    networks:
      - blacktree-net

    restart: unless-stopped

networks:
  blacktree-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
